spring.application.name=proveedores

# Configuración de Base de Datos (Clever Cloud)
spring.datasource.url=jdbc:mysql://bv97bs4agdi6xnhijsf4-mysql.services.clever-cloud.com:3306/bv97bs4agdi6xnhijsf4
spring.datasource.username=ueiv0etteujbrrep
spring.datasource.password=Mvw7U4Yj9xY23N77Uj9R
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=2

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
